<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5VI0HAR" failures="1" tests="4" name="PetTest" time="7.188" errors="0" timestamp="2024-02-07T22:50:34 CST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="3.938"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="0.373"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="0.293"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="0.337">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testDeleteUserByName(UserTests.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- PetTest -->
